# Generated by Django 4.0.5 on 2022-06-11 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tamplatesCreate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='singleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='postType',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tamplatesCreate.posttype'),
        ),
        migrations.AddField(
            model_name='post',
            name='singleType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tamplatesCreate.singletype'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
